id: IDCB82F94
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:26:31+00:00'
last_modified: '2022-06-08T11:01:28.311531+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2862
  title: ཟབ་མོ་ནང་དོན་གྱི་འགྲེལ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6C8E:
      image_group_id: I3CN2864
      title: ''
      total_pages: 810
      order: 1
      base_file: 6C8E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
