id: IDCB82F94
legacy_id: P009436
ocr_import_info:
  bdrc_scan_id: W3CN2862
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T03:20:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:10:34.732043+00:00'
last_modified: 2022-09-03 21:10:57.667542
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN2862
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN2862
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟབ་མོ་ནང་དོན་གྱི་འགྲེལ་བཤད།
  author: དྭགས་རམས་པ་ཆོས་རྒྱལ་བསྟན་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6361228880735825
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I3CN2864:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2864
      total_pages: 810
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2864.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6361228880735825
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
